### ISSUE TITLE
Complete All Difficulties

### ISSUE THREAD

**Issue by SethClydesdale** [SethClydesdale/typing-with-mishy#1]
I released Typing with Mishy early to gather feedback while I work on the additional difficulties. So at launch only Easy mode was available. 

Whenever a new difficulty is completed I will check it off on the list below! You can also [follow me on Twitter](https://twitter.com/SethC1995) for updates as well.

**TODO**
- [x] Easy - "Day with Mishy" (Completed: 09/17/2020)
- [x] Normal - "Dream with Mishy" (Completed: 09/27/2020)
- [x] Hard - "Date with Mishy" (Completed: 10/05/2020)
- [x] Nightmare - "Trails with Mishy" (Completed: 10/11/2020)
- [x] Infinity - "Challenge with Mishy" (Completed: 10/11/2020)

Look forward to more of Mishy's adventures!

**Overall Development Time:** August 20, 2020 to October 11, 2020

**Ideas:** I'd also like to make an Ys-like game featuring Mishy.. maybe one day.

**Comment by SethClydesdale** [comment]
All difficulties are finally complete! Please see [the readme](https://github.com/SethClydesdale/typing-with-mishy#readme) for info on playing the game.

Enjoy Mishy!
